grafana:
  enabled: false

alertmanager:
  enabled: false

prometheus:
  prometheusSpec:
    retention: 24h
    scrapeInterval: 30s
    evaluationInterval: 30s

    resources:
      requests:
        memory: 100Mi
        cpu: 100m
      limits:
        memory: 300Mi
        cpu: 200m
